export const BLOG_DATA = {
  data: {
    data: [
      {
        url: 'nintendo-is-having-pokemon-direct-tomorrow',
        created: '2019-02-26T16:21:46.254089Z',
        published: '2019-02-26T16:21:00Z',
        author: {
          first_name: 'Sam',
          last_name: 'Hudgens',
          email: 'sam@openforge.io',
          slug: 'sam-hudgens',
          bio: '',
          title: '',
          linkedin_url: '',
          facebook_url: '',
          instagram_url: '',
          pinterest_url: '',
          twitter_handle: '',
          profile_image: '',
        },
        categories: [
          {
            name: 'nintendo',
            slug: 'nintendo',
          },
        ],
        tags: [
          {
            name: 'nintendo',
            slug: 'nintendo',
          },
        ],
        featured_image: null,
        slug: 'nintendo-is-having-pokemon-direct-tomorrow',
        title: 'Nintendo is having Pokemon Direct tomorrow',
        summary: 'My uncle works at nintendo and told me',
        seo_title: 'Nintendo is having Pokemon Direct tomorrow',
        meta_description: 'jump',
        status: 'published',
        cloned_source: null,
      },
      {
        url: 'i-heard-if-you-eat-36-eggs-per-day-its-as-good-as-doing-steroids',
        created: '2019-02-26T16:22:26.599245Z',
        published: '2019-02-26T16:21:00Z',
        author: {
          first_name: 'Sam',
          last_name: 'Hudgens',
          email: 'sam@openforge.io',
          slug: 'sam-hudgens',
          bio: '',
          title: '',
          linkedin_url: '',
          facebook_url: '',
          instagram_url: '',
          pinterest_url: '',
          twitter_handle: '',
          profile_image: '',
        },
        categories: [
          {
            name: 'fitness',
            slug: 'fitness',
          },
        ],
        tags: [
          {
            name: 'fitness',
            slug: 'fitness',
          },
          {
            name: 'swole',
            slug: 'swole',
          },
        ],
        featured_image: null,
        slug: 'i-heard-if-you-eat-36-eggs-per-day-its-as-good-as-doing-steroids',
        title: "I heard if you eat 36 eggs per day it's as good as doing steroids",
        summary: 'Gonna get swole',
        seo_title: "I heard if you eat 36 eggs per day it's as good as doing steroids",
        meta_description: 'get swole',
        status: 'published',
        cloned_source: null,
      },
      {
        url: 'green-goo-won-the-oscars',
        created: '2019-02-26T16:20:58.200105Z',
        published: '2019-02-26T16:20:00Z',
        author: {
          first_name: 'Sam',
          last_name: 'Hudgens',
          email: 'sam@openforge.io',
          slug: 'sam-hudgens',
          bio: '',
          title: '',
          linkedin_url: '',
          facebook_url: '',
          instagram_url: '',
          pinterest_url: '',
          twitter_handle: '',
          profile_image: '',
        },
        categories: [
          {
            name: 'movies',
            slug: 'movies',
          },
        ],
        tags: [
          {
            name: 'oscars',
            slug: 'oscars',
          },
        ],
        featured_image: null,
        slug: 'green-goo-won-the-oscars',
        title: 'Green Goo won the oscars',
        summary: 'Never even heard of that movie',
        seo_title: 'Green Goo won the oscars',
        meta_description: 'hollywood',
        status: 'published',
        cloned_source: null,
      },
      {
        url: 'blog-content',
        created: '2019-02-26T16:20:18.450653Z',
        published: '2019-02-26T16:19:00Z',
        author: {
          first_name: 'Sam',
          last_name: 'Hudgens',
          email: 'sam@openforge.io',
          slug: 'sam-hudgens',
          bio: '',
          title: '',
          linkedin_url: '',
          facebook_url: '',
          instagram_url: '',
          pinterest_url: '',
          twitter_handle: '',
          profile_image: '',
        },
        categories: [
          {
            name: 'gossip',
            slug: 'gossip',
          },
        ],
        tags: [
          {
            name: 'sports',
            slug: 'sports',
          },
        ],
        featured_image: null,
        slug: 'blog-content',
        title: 'Blog content',
        summary: 'Green Goo won the Oscars',
        seo_title: 'Blog content',
        meta_description: 'Green Goo won the Oscars',
        status: 'published',
        cloned_source: null,
      },
      {
        url: 'kim-kardashian-did-what',
        created: '2019-02-26T16:17:39.666878Z',
        published: '2019-02-26T16:16:00Z',
        author: {
          first_name: 'Sam',
          last_name: 'Hudgens',
          email: 'sam@openforge.io',
          slug: 'sam-hudgens',
          bio: '',
          title: '',
          linkedin_url: '',
          facebook_url: '',
          instagram_url: '',
          pinterest_url: '',
          twitter_handle: '',
          profile_image: '',
        },
        categories: [
          {
            name: 'gossip',
            slug: 'gossip',
          },
        ],
        tags: [
          {
            name: 'kardashian',
            slug: 'kardashian',
          },
          {
            name: 'kim kardashian',
            slug: 'kim-kardashian',
          },
        ],
        featured_image: null,
        slug: 'kim-kardashian-did-what',
        title: 'Kim Kardashian said WHAT?!',
        summary: 'Kim K is at it again',
        seo_title: 'Kim Kardashian did WHAT?!',
        meta_description: 'Kim Kardashian kourts kontroversy',
        status: 'published',
        cloned_source: null,
      },
      {
        url: 'test-new-blog-post',
        created: '2019-02-25T16:44:34.965955Z',
        published: '2019-02-25T16:43:00Z',
        author: {
          first_name: 'Matt',
          last_name: 'Moran',
          email: 'matt@openforge.io',
          slug: 'matt-moran',
          bio: '',
          title: '',
          linkedin_url: '',
          facebook_url: '',
          instagram_url: '',
          pinterest_url: '',
          twitter_handle: '',
          profile_image: '',
        },
        categories: [
          {
            name: 'blog',
            slug: 'blog',
          },
          {
            name: 'dev',
            slug: 'dev',
          },
        ],
        tags: [
          {
            name: 'apple',
            slug: 'apple',
          },
          {
            name: 'matt',
            slug: 'matt',
          },
          {
            name: 'sam',
            slug: 'sam',
          },
        ],
        featured_image: 'https://d2wzhk7xhrnk1x.cloudfront.net/f9Sen4QQcyVHSDZzI75w_butter-blog-post.jpg',
        slug: 'test-new-blog-post',
        title: 'Test New blog post',
        summary: 'What is a summary?',
        seo_title: 'Game of Thrones',
        meta_description: 'Kim Kardashian',
        status: 'published',
        cloned_source: null,
      },
      {
        url: 'example-post',
        created: '2019-02-25T15:44:56.149003Z',
        published: '2019-02-25T15:44:56.148168Z',
        author: {
          first_name: 'Receipts',
          last_name: 'Account',
          email: 'receipts@openforge.io',
          slug: 'receipts-account',
          bio: '',
          title: '',
          linkedin_url: '',
          facebook_url: '',
          instagram_url: '',
          pinterest_url: '',
          twitter_handle: '',
          profile_image: 'https://lh4.googleusercontent.com/-oIaMIhi_854/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rdGNqqJMy1SZv9Om_Ap5qSZ9twO3Q/mo/photo.jpg',
        },
        categories: [
          {
            name: 'Example Category',
            slug: 'example-category',
          },
        ],
        tags: [
          {
            name: 'Example Tag',
            slug: 'example-tag',
          },
        ],
        featured_image: 'https://d2devwt40at1e2.cloudfront.net/api/file/tdt3s1OHRO6wfQOpmAHw',
        slug: 'example-post',
        title: 'Example Post',
        summary: 'This is an example blog post. Pretty neat huh?',
        seo_title: 'Example Post SEO Optimized Title',
        meta_description: 'This is our example blog posts SEO optimized meta description.',
        status: 'published',
        cloned_source: null,
      },
    ],
    meta: {
      previous_page: null,
      next_page: null,
      count: 7,
    },
  },
  status: 200,
  statusText: 'OK',
  headers: {
    server: 'gunicorn/19.9.0',
    'content-type': 'application/json',
    'x-frame-options': 'SAMEORIGIN',
    allow: 'GET, HEAD, OPTIONS',
    via: '1.1 vegur, 1.1 varnish, 1.1 varnish',
    'access-control-allow-origin': '*',
    'content-length': '5532',
    'accept-ranges': 'bytes',
    date: 'Mon, 04 Mar 2019 18:00:02 GMT',
    age: '11364',
    connection: 'close',
    'x-served-by': 'cache-iad2142-IAD, cache-jfk8136-JFK',
    'x-cache': 'MISS, HIT',
    'x-cache-hits': '0, 2',
    'x-timer': 'S1551722402.378473,VS0,VE6',
  },
  config: {
    transformRequest: [null],
    transformResponse: [null],
    headers: {
      Accept: 'application/json, text/plain, */*',
      'X-Butter-Client': 'JS/1.1.3',
      'User-Agent': 'axios/0.9.1',
    },
    timeout: 3000,
    xsrfCookieName: 'XSRF-TOKEN',
    xsrfHeaderName: 'X-XSRF-TOKEN',
    baseURL: 'https://api.buttercms.com/v2',
    method: 'get',
    params: {
      page: 1,
      page_size: 100000,
      exclude_body: true,
      auth_token: 'fca1bc914c05371263f98c9d3480eaa215fd63d6',
    },
    url: 'https://api.buttercms.com/v2/posts/',
  },
};
