export const BLOG_DATA = {
  meta: {
    previous_page: null,
    next_page: null,
    count: 7,
  },
  data: [
    {
      url: 'i-heard-if-you-eat-36-eggs-per-day-its-as-good-as-doing-steroids',
      created: '2019-02-26T16:22:26.599245Z',
      published: '2019-02-26T16:21:00Z',
      author: {
        first_name: 'Sam',
        last_name: 'Hudgens',
        email: 'sam@openforge.io',
        slug: 'sam-hudgens',
        bio: '',
        title: '',
        linkedin_url: '',
        facebook_url: '',
        instagram_url: '',
        pinterest_url: '',
        twitter_handle: '',
        profile_image: 'https://d2wzhk7xhrnk1x.cloudfront.net/f9Sen4QQcyVHSDZzI75w_butter-blog-post.jpg',
      },
      categories: [
        {
          name: 'Business',
          slug: 'business',
        },
      ],
      tags: [
        {
          name: 'featured',
          slug: 'featured',
        },
        {
          name: 'fitness',
          slug: 'fitness',
        },
        {
          name: 'swole',
          slug: 'swole',
        },
      ],
      featured_image: 'https://d2wzhk7xhrnk1x.cloudfront.net/f9Sen4QQcyVHSDZzI75w_butter-blog-post.jpg',
      slug: 'i-heard-if-you-eat-36-eggs-per-day-its-as-good-as-doing-steroids',
      title: "I heard if you eat 36 eggs per day it's as good as doing steroids",
      body:
        '<p>Gonna get swole&nbsp;<span>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</span></p>',
      summary: 'Gonna get swole  Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.',
      seo_title: "I heard if you eat 36 eggs per day it's as good as doing steroids",
      meta_description: 'get swole',
      status: 'published',
      cloned_source: null,
    },
    {
      url: 'nintendo-is-having-pokemon-direct-tomorrow',
      created: '2019-02-26T16:21:46.254089Z',
      published: '2019-02-26T16:21:00Z',
      author: {
        first_name: 'Sam',
        last_name: 'Hudgens',
        email: 'sam@openforge.io',
        slug: 'sam-hudgens',
        bio: '',
        title: '',
        linkedin_url: '',
        facebook_url: '',
        instagram_url: '',
        pinterest_url: '',
        twitter_handle: '',
        profile_image: 'https://d2wzhk7xhrnk1x.cloudfront.net/f9Sen4QQcyVHSDZzI75w_butter-blog-post.jpg',
      },
      categories: [],
      tags: [
        {
          name: 'nintendo',
          slug: 'nintendo',
        },
      ],
      featured_image: 'https://d2wzhk7xhrnk1x.cloudfront.net/f9Sen4QQcyVHSDZzI75w_butter-blog-post.jpg',
      slug: 'nintendo-is-having-pokemon-direct-tomorrow',
      title: 'Nintendo is having Pokemon Direct tomorrow',
      body: '<p>My uncle works at nintendo and told me</p>',
      summary: 'My uncle works at nintendo and told me',
      seo_title: 'Nintendo is having Pokemon Direct tomorrow',
      meta_description: 'jump',
      status: 'published',
      cloned_source: null,
    },
    {
      url: 'green-goo-won-the-oscars',
      created: '2019-02-26T16:20:58.200105Z',
      published: '2019-02-26T16:20:00Z',
      author: {
        first_name: 'Sam',
        last_name: 'Hudgens',
        email: 'sam@openforge.io',
        slug: 'sam-hudgens',
        bio: '',
        title: '',
        linkedin_url: '',
        facebook_url: '',
        instagram_url: '',
        pinterest_url: '',
        twitter_handle: '',
        profile_image: 'https://d2wzhk7xhrnk1x.cloudfront.net/f9Sen4QQcyVHSDZzI75w_butter-blog-post.jpg',
      },
      categories: [],
      tags: [
        {
          name: 'oscars',
          slug: 'oscars',
        },
      ],
      featured_image: 'https://d2wzhk7xhrnk1x.cloudfront.net/f9Sen4QQcyVHSDZzI75w_butter-blog-post.jpg',
      slug: 'green-goo-won-the-oscars',
      title: 'Butter laughs at your miserable attempts to Prerender',
      body: '<p>Ha!</p>',
      summary: 'Never even heard of that movie',
      seo_title: 'Green Goo won the oscars',
      meta_description: 'hollywood',
      status: 'published',
      cloned_source: null,
    },
    {
      url: 'blog-content',
      created: '2019-02-26T16:20:18.450653Z',
      published: '2019-02-26T16:19:00Z',
      author: {
        first_name: 'Sam',
        last_name: 'Hudgens',
        email: 'sam@openforge.io',
        slug: 'sam-hudgens',
        bio: '',
        title: '',
        linkedin_url: '',
        facebook_url: '',
        instagram_url: '',
        pinterest_url: '',
        twitter_handle: '',
        profile_image: 'https://d2wzhk7xhrnk1x.cloudfront.net/f9Sen4QQcyVHSDZzI75w_butter-blog-post.jpg',
      },
      categories: [],
      tags: [
        {
          name: 'sports',
          slug: 'sports',
        },
      ],
      featured_image: 'https://d2wzhk7xhrnk1x.cloudfront.net/f9Sen4QQcyVHSDZzI75w_butter-blog-post.jpg',
      slug: 'blog-content',
      title: 'Blog content',
      body: '<p>hello</p>',
      summary: 'Green Goo won the Oscars',
      seo_title: 'Blog content',
      meta_description: 'Green Goo won the Oscars',
      status: 'published',
      cloned_source: null,
    },
    {
      url: 'kim-kardashian-did-what',
      created: '2019-02-26T16:17:39.666878Z',
      published: '2019-02-26T16:16:00Z',
      author: {
        first_name: 'Sam',
        last_name: 'Hudgens',
        email: 'sam@openforge.io',
        slug: 'sam-hudgens',
        bio: '',
        title: '',
        linkedin_url: '',
        facebook_url: '',
        instagram_url: '',
        pinterest_url: '',
        twitter_handle: '',
        profile_image: 'https://d2wzhk7xhrnk1x.cloudfront.net/f9Sen4QQcyVHSDZzI75w_butter-blog-post.jpg',
      },
      categories: [
        {
          name: 'Development',
          slug: 'development',
        },
      ],
      tags: [
        {
          name: 'kardashian',
          slug: 'kardashian',
        },
        {
          name: 'kim kardashian',
          slug: 'kim-kardashian',
        },
      ],
      featured_image: 'https://d2wzhk7xhrnk1x.cloudfront.net/f9Sen4QQcyVHSDZzI75w_butter-blog-post.jpg',
      slug: 'kim-kardashian-did-what',
      title: 'Kim Kardashian said WHAT?!',
      body: '<p>Kim K is at it again</p>',
      summary: 'Kim K is at it again',
      seo_title: 'Kim Kardashian did WHAT?!',
      meta_description: 'Kim Kardashian kourts kontroversy',
      status: 'published',
      cloned_source: null,
    },
    {
      url: 'test-new-blog-post',
      created: '2019-02-25T16:44:34.965955Z',
      published: '2019-02-25T16:43:00Z',
      author: {
        first_name: 'Matt',
        last_name: 'Moran',
        email: 'matt@openforge.io',
        slug: 'matt-moran',
        bio: '',
        title: '',
        linkedin_url: '',
        facebook_url: '',
        instagram_url: '',
        pinterest_url: '',
        twitter_handle: '',
        profile_image: 'https://d2wzhk7xhrnk1x.cloudfront.net/f9Sen4QQcyVHSDZzI75w_butter-blog-post.jpg',
      },
      categories: [
        {
          name: 'Announcements',
          slug: 'announcements',
        },
      ],
      tags: [
        {
          name: 'apple',
          slug: 'apple',
        },
        {
          name: 'matt',
          slug: 'matt',
        },
        {
          name: 'sam',
          slug: 'sam',
        },
      ],
      featured_image: 'https://d2wzhk7xhrnk1x.cloudfront.net/f9Sen4QQcyVHSDZzI75w_butter-blog-post.jpg',
      slug: 'test-new-blog-post',
      title: 'Test New blog post',
      body: '<p>Matt and Sam are creating a blog post</p>',
      summary: 'What is a summary?',
      seo_title: 'Game of Thrones',
      meta_description: 'Kim Kardashian',
      status: 'published',
      cloned_source: null,
    },
    {
      url: 'example-post',
      created: '2019-02-25T15:44:56.149003Z',
      published: '2019-02-25T15:44:56.148168Z',
      author: {
        first_name: 'Receipts',
        last_name: 'Account',
        email: 'receipts@openforge.io',
        slug: 'receipts-account',
        bio: '',
        title: '',
        linkedin_url: '',
        facebook_url: '',
        instagram_url: '',
        pinterest_url: '',
        twitter_handle: '',
        profile_image: 'https://lh4.googleusercontent.com/-oIaMIhi_854/AAAAAAAAAAI/AAAAAAAAAAA/ACHi3rdGNqqJMy1SZv9Om_Ap5qSZ9twO3Q/mo/photo.jpg',
      },
      categories: [
        {
          name: 'Design',
          slug: 'design',
        },
      ],
      tags: [
        {
          name: 'Example Tag',
          slug: 'example-tag',
        },
      ],
      featured_image: 'https://d2devwt40at1e2.cloudfront.net/api/file/tdt3s1OHRO6wfQOpmAHw',
      slug: 'example-post',
      title: 'Example Post',
      body:
        '<p>Welcome to ButterCMS! This an example blog post written using Butter.</p>\n<h3>What\'s happening here?</h3>\n<p>If you\'re viewing this post from your website or command line, you\'ve successfully made a request to&nbsp;the <a href="https://buttercms.com/docs/api">Butter API</a>. If you haven\'t already, make sure you have our <a href="https://buttercms.com/docs/">development guides</a> pulled up for step-by-step instructions on setting up Butter.</p>\n<h3>How does&nbsp;editing work?</h3>\n<p>Butter\'s WYSIWYG editor supports standard text formatting including headings, links, quotes, code, text alignment, and more. You can upload, crop, and resize images which are automatically hosted and delivered through a CDN (see below). You can also edit HTML directly when needed.</p>\n<figure class="image"><img src="https://d2wzhk7xhrnk1x.cloudfront.net/rgPM9aHoSSKnjk44TQlD_butter-blog-post.jpg" alt="Delivered to you via CDN" />\n<figcaption>Delivered to you via CDN</figcaption>\n</figure>\n<h3>Can I use Butter as a full CMS for&nbsp;things other than a&nbsp;blog?</h3>\n<p>Yes. Butter can be used as a full CMS for managing dynamic content and creating pages across your entire website or app. Check out our <a href="https://buttercms.com/docs/">development guides</a> for step-by-step tutorials on setting this up.</p>\n',
      summary: 'This is an example blog post. Pretty neat huh?',
      seo_title: 'Example Post SEO Optimized Title',
      meta_description: 'This is our example blog posts SEO optimized meta description.',
      status: 'published',
      cloned_source: null,
    },
  ],
};
