/* tslint:disable */
/**
 * This is an autogenerated file created by the Stencil compiler.
 * It contains typing information for all components that exist in this project.
 */


import '@stencil/core';

import '@stencil/router';
import '@stencil/state-tunnel';
import {
  BlogPost,
} from './model/blog-post.model';
import {
  EventEmitter,
} from '@stencil/core';
import {
  MatchResults,
  RouterHistory,
} from '@stencil/router';


export namespace Components {

  interface AppBlogCard {
    'blogPost': BlogPost;
  }
  interface AppBlogCardAttributes extends StencilHTMLAttributes {
    'blogPost'?: BlogPost;
  }

  interface AppBlogContent {
    'blogPost': BlogPost;
  }
  interface AppBlogContentAttributes extends StencilHTMLAttributes {
    'blogPost'?: BlogPost;
  }

  interface AppBlogFeatured {
    'blogPost': BlogPost;
  }
  interface AppBlogFeaturedAttributes extends StencilHTMLAttributes {
    'blogPost'?: BlogPost;
  }

  interface AppCarouselIndicators {
    'activeIndex': string;
  }
  interface AppCarouselIndicatorsAttributes extends StencilHTMLAttributes {
    'activeIndex'?: string;
  }

  interface AppCta {}
  interface AppCtaAttributes extends StencilHTMLAttributes {}

  interface AppFooter {}
  interface AppFooterAttributes extends StencilHTMLAttributes {}

  interface AppImg {
    'alt': string;
    'fit': boolean;
    'preLoad': boolean;
    'src': string;
  }
  interface AppImgAttributes extends StencilHTMLAttributes {
    'alt'?: string;
    'fit'?: boolean;
    'preLoad'?: boolean;
    'src'?: string;
  }

  interface LazyImg {
    'alt': string;
    'src': string;
    'width': number;
  }
  interface LazyImgAttributes extends StencilHTMLAttributes {
    'alt'?: string;
    'onLazyImgloaded'?: (event: CustomEvent<HTMLImageElement>) => void;
    'src'?: string;
    'width'?: number;
  }

  interface AppInput {
    'id': string;
    'label': string;
    'maxlength': string;
    'name': string;
    'placeholder': string;
    'required': boolean;
    'type': string;
  }
  interface AppInputAttributes extends StencilHTMLAttributes {
    'id'?: string;
    'label'?: string;
    'maxlength'?: string;
    'name'?: string;
    'onValueChange'?: (event: CustomEvent) => void;
    'placeholder'?: string;
    'required'?: boolean;
    'type'?: string;
  }

  interface AppMembers {
    'members': any[];
  }
  interface AppMembersAttributes extends StencilHTMLAttributes {
    'members'?: any[];
  }

  interface AppNavHeader {}
  interface AppNavHeaderAttributes extends StencilHTMLAttributes {}

  interface AppRadio {
    'label': string;
    'name': string;
    'required': boolean;
    'value': string;
  }
  interface AppRadioAttributes extends StencilHTMLAttributes {
    'label'?: string;
    'name'?: string;
    'onValueChange'?: (event: CustomEvent) => void;
    'required'?: boolean;
    'value'?: string;
  }

  interface AppSlider {
    'label': string;
    'name': string;
  }
  interface AppSliderAttributes extends StencilHTMLAttributes {
    'label'?: string;
    'name'?: string;
    'onValueChange'?: (event: CustomEvent) => void;
  }

  interface AppTextarea {
    'id': string;
    'label': string;
    'maxlength': string;
    'name': string;
    'placeholder': string;
    'required': boolean;
    'rows': number;
  }
  interface AppTextareaAttributes extends StencilHTMLAttributes {
    'id'?: string;
    'label'?: string;
    'maxlength'?: string;
    'name'?: string;
    'onValueChange'?: (event: CustomEvent) => void;
    'placeholder'?: string;
    'required'?: boolean;
    'rows'?: number;
  }

  interface AppTranslate {
    'key': string;
    'params': {};
  }
  interface AppTranslateAttributes extends StencilHTMLAttributes {
    'key'?: string;
    'params'?: {};
  }

  interface ContentGraphic {
    'imgUrl': string;
    'preLoadImg': boolean;
    'reverse': boolean;
  }
  interface ContentGraphicAttributes extends StencilHTMLAttributes {
    'imgUrl'?: string;
    'preLoadImg'?: boolean;
    'reverse'?: boolean;
  }

  interface App404 {}
  interface App404Attributes extends StencilHTMLAttributes {}

  interface AppAbout {}
  interface AppAboutAttributes extends StencilHTMLAttributes {}

  interface AppBlogIndex {
    'butter': any;
  }
  interface AppBlogIndexAttributes extends StencilHTMLAttributes {
    'butter'?: any;
  }

  interface AppBlogPost {
    'butter': any;
    'history': RouterHistory;
    'match': MatchResults;
    'preRenderBlogPost': BlogPost;
  }
  interface AppBlogPostAttributes extends StencilHTMLAttributes {
    'butter'?: any;
    'history'?: RouterHistory;
    'match'?: MatchResults;
    'preRenderBlogPost'?: BlogPost;
  }

  interface AppBlog {
    'butter': any;
  }
  interface AppBlogAttributes extends StencilHTMLAttributes {
    'butter'?: any;
  }

  interface AppCaseStudy {}
  interface AppCaseStudyAttributes extends StencilHTMLAttributes {}

  interface AppContact {
    'errorIconStyles': any;
  }
  interface AppContactAttributes extends StencilHTMLAttributes {
    'errorIconStyles'?: any;
  }

  interface AppDetailedService {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppDetailedServiceAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface AppHome {
    'butter': any;
    'history': RouterHistory;
  }
  interface AppHomeAttributes extends StencilHTMLAttributes {
    'butter'?: any;
    'history'?: RouterHistory;
  }

  interface AppOpportunities {
    'errorIconStyles': any;
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppOpportunitiesAttributes extends StencilHTMLAttributes {
    'errorIconStyles'?: any;
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface AppResources {
    'errorIconStyles': any;
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppResourcesAttributes extends StencilHTMLAttributes {
    'errorIconStyles'?: any;
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface AppServiceLevelAgreement {}
  interface AppServiceLevelAgreementAttributes extends StencilHTMLAttributes {}

  interface AppServices {}
  interface AppServicesAttributes extends StencilHTMLAttributes {}

  interface AppTeamLanding {
    'history': RouterHistory;
    'match': MatchResults;
  }
  interface AppTeamLandingAttributes extends StencilHTMLAttributes {
    'history'?: RouterHistory;
    'match'?: MatchResults;
  }

  interface AppToolbox {}
  interface AppToolboxAttributes extends StencilHTMLAttributes {}

  interface AppTos {}
  interface AppTosAttributes extends StencilHTMLAttributes {}

  interface OpenForgeApp {}
  interface OpenForgeAppAttributes extends StencilHTMLAttributes {}
}

declare global {
  interface StencilElementInterfaces {
    'AppBlogCard': Components.AppBlogCard;
    'AppBlogContent': Components.AppBlogContent;
    'AppBlogFeatured': Components.AppBlogFeatured;
    'AppCarouselIndicators': Components.AppCarouselIndicators;
    'AppCta': Components.AppCta;
    'AppFooter': Components.AppFooter;
    'AppImg': Components.AppImg;
    'LazyImg': Components.LazyImg;
    'AppInput': Components.AppInput;
    'AppMembers': Components.AppMembers;
    'AppNavHeader': Components.AppNavHeader;
    'AppRadio': Components.AppRadio;
    'AppSlider': Components.AppSlider;
    'AppTextarea': Components.AppTextarea;
    'AppTranslate': Components.AppTranslate;
    'ContentGraphic': Components.ContentGraphic;
    'App404': Components.App404;
    'AppAbout': Components.AppAbout;
    'AppBlogIndex': Components.AppBlogIndex;
    'AppBlogPost': Components.AppBlogPost;
    'AppBlog': Components.AppBlog;
    'AppCaseStudy': Components.AppCaseStudy;
    'AppContact': Components.AppContact;
    'AppDetailedService': Components.AppDetailedService;
    'AppHome': Components.AppHome;
    'AppOpportunities': Components.AppOpportunities;
    'AppResources': Components.AppResources;
    'AppServiceLevelAgreement': Components.AppServiceLevelAgreement;
    'AppServices': Components.AppServices;
    'AppTeamLanding': Components.AppTeamLanding;
    'AppToolbox': Components.AppToolbox;
    'AppTos': Components.AppTos;
    'OpenForgeApp': Components.OpenForgeApp;
  }

  interface StencilIntrinsicElements {
    'app-blog-card': Components.AppBlogCardAttributes;
    'app-blog-content': Components.AppBlogContentAttributes;
    'app-blog-featured': Components.AppBlogFeaturedAttributes;
    'app-carousel-indicators': Components.AppCarouselIndicatorsAttributes;
    'app-cta': Components.AppCtaAttributes;
    'app-footer': Components.AppFooterAttributes;
    'app-img': Components.AppImgAttributes;
    'lazy-img': Components.LazyImgAttributes;
    'app-input': Components.AppInputAttributes;
    'app-members': Components.AppMembersAttributes;
    'app-nav-header': Components.AppNavHeaderAttributes;
    'app-radio': Components.AppRadioAttributes;
    'app-slider': Components.AppSliderAttributes;
    'app-textarea': Components.AppTextareaAttributes;
    'app-translate': Components.AppTranslateAttributes;
    'content-graphic': Components.ContentGraphicAttributes;
    'app-404': Components.App404Attributes;
    'app-about': Components.AppAboutAttributes;
    'app-blog-index': Components.AppBlogIndexAttributes;
    'app-blog-post': Components.AppBlogPostAttributes;
    'app-blog': Components.AppBlogAttributes;
    'app-case-study': Components.AppCaseStudyAttributes;
    'app-contact': Components.AppContactAttributes;
    'app-detailed-service': Components.AppDetailedServiceAttributes;
    'app-home': Components.AppHomeAttributes;
    'app-opportunities': Components.AppOpportunitiesAttributes;
    'app-resources': Components.AppResourcesAttributes;
    'app-service-level-agreement': Components.AppServiceLevelAgreementAttributes;
    'app-services': Components.AppServicesAttributes;
    'app-team-landing': Components.AppTeamLandingAttributes;
    'app-toolbox': Components.AppToolboxAttributes;
    'app-tos': Components.AppTosAttributes;
    'open-forge-app': Components.OpenForgeAppAttributes;
  }


  interface HTMLAppBlogCardElement extends Components.AppBlogCard, HTMLStencilElement {}
  var HTMLAppBlogCardElement: {
    prototype: HTMLAppBlogCardElement;
    new (): HTMLAppBlogCardElement;
  };

  interface HTMLAppBlogContentElement extends Components.AppBlogContent, HTMLStencilElement {}
  var HTMLAppBlogContentElement: {
    prototype: HTMLAppBlogContentElement;
    new (): HTMLAppBlogContentElement;
  };

  interface HTMLAppBlogFeaturedElement extends Components.AppBlogFeatured, HTMLStencilElement {}
  var HTMLAppBlogFeaturedElement: {
    prototype: HTMLAppBlogFeaturedElement;
    new (): HTMLAppBlogFeaturedElement;
  };

  interface HTMLAppCarouselIndicatorsElement extends Components.AppCarouselIndicators, HTMLStencilElement {}
  var HTMLAppCarouselIndicatorsElement: {
    prototype: HTMLAppCarouselIndicatorsElement;
    new (): HTMLAppCarouselIndicatorsElement;
  };

  interface HTMLAppCtaElement extends Components.AppCta, HTMLStencilElement {}
  var HTMLAppCtaElement: {
    prototype: HTMLAppCtaElement;
    new (): HTMLAppCtaElement;
  };

  interface HTMLAppFooterElement extends Components.AppFooter, HTMLStencilElement {}
  var HTMLAppFooterElement: {
    prototype: HTMLAppFooterElement;
    new (): HTMLAppFooterElement;
  };

  interface HTMLAppImgElement extends Components.AppImg, HTMLStencilElement {}
  var HTMLAppImgElement: {
    prototype: HTMLAppImgElement;
    new (): HTMLAppImgElement;
  };

  interface HTMLLazyImgElement extends Components.LazyImg, HTMLStencilElement {}
  var HTMLLazyImgElement: {
    prototype: HTMLLazyImgElement;
    new (): HTMLLazyImgElement;
  };

  interface HTMLAppInputElement extends Components.AppInput, HTMLStencilElement {}
  var HTMLAppInputElement: {
    prototype: HTMLAppInputElement;
    new (): HTMLAppInputElement;
  };

  interface HTMLAppMembersElement extends Components.AppMembers, HTMLStencilElement {}
  var HTMLAppMembersElement: {
    prototype: HTMLAppMembersElement;
    new (): HTMLAppMembersElement;
  };

  interface HTMLAppNavHeaderElement extends Components.AppNavHeader, HTMLStencilElement {}
  var HTMLAppNavHeaderElement: {
    prototype: HTMLAppNavHeaderElement;
    new (): HTMLAppNavHeaderElement;
  };

  interface HTMLAppRadioElement extends Components.AppRadio, HTMLStencilElement {}
  var HTMLAppRadioElement: {
    prototype: HTMLAppRadioElement;
    new (): HTMLAppRadioElement;
  };

  interface HTMLAppSliderElement extends Components.AppSlider, HTMLStencilElement {}
  var HTMLAppSliderElement: {
    prototype: HTMLAppSliderElement;
    new (): HTMLAppSliderElement;
  };

  interface HTMLAppTextareaElement extends Components.AppTextarea, HTMLStencilElement {}
  var HTMLAppTextareaElement: {
    prototype: HTMLAppTextareaElement;
    new (): HTMLAppTextareaElement;
  };

  interface HTMLAppTranslateElement extends Components.AppTranslate, HTMLStencilElement {}
  var HTMLAppTranslateElement: {
    prototype: HTMLAppTranslateElement;
    new (): HTMLAppTranslateElement;
  };

  interface HTMLContentGraphicElement extends Components.ContentGraphic, HTMLStencilElement {}
  var HTMLContentGraphicElement: {
    prototype: HTMLContentGraphicElement;
    new (): HTMLContentGraphicElement;
  };

  interface HTMLApp404Element extends Components.App404, HTMLStencilElement {}
  var HTMLApp404Element: {
    prototype: HTMLApp404Element;
    new (): HTMLApp404Element;
  };

  interface HTMLAppAboutElement extends Components.AppAbout, HTMLStencilElement {}
  var HTMLAppAboutElement: {
    prototype: HTMLAppAboutElement;
    new (): HTMLAppAboutElement;
  };

  interface HTMLAppBlogIndexElement extends Components.AppBlogIndex, HTMLStencilElement {}
  var HTMLAppBlogIndexElement: {
    prototype: HTMLAppBlogIndexElement;
    new (): HTMLAppBlogIndexElement;
  };

  interface HTMLAppBlogPostElement extends Components.AppBlogPost, HTMLStencilElement {}
  var HTMLAppBlogPostElement: {
    prototype: HTMLAppBlogPostElement;
    new (): HTMLAppBlogPostElement;
  };

  interface HTMLAppBlogElement extends Components.AppBlog, HTMLStencilElement {}
  var HTMLAppBlogElement: {
    prototype: HTMLAppBlogElement;
    new (): HTMLAppBlogElement;
  };

  interface HTMLAppCaseStudyElement extends Components.AppCaseStudy, HTMLStencilElement {}
  var HTMLAppCaseStudyElement: {
    prototype: HTMLAppCaseStudyElement;
    new (): HTMLAppCaseStudyElement;
  };

  interface HTMLAppContactElement extends Components.AppContact, HTMLStencilElement {}
  var HTMLAppContactElement: {
    prototype: HTMLAppContactElement;
    new (): HTMLAppContactElement;
  };

  interface HTMLAppDetailedServiceElement extends Components.AppDetailedService, HTMLStencilElement {}
  var HTMLAppDetailedServiceElement: {
    prototype: HTMLAppDetailedServiceElement;
    new (): HTMLAppDetailedServiceElement;
  };

  interface HTMLAppHomeElement extends Components.AppHome, HTMLStencilElement {}
  var HTMLAppHomeElement: {
    prototype: HTMLAppHomeElement;
    new (): HTMLAppHomeElement;
  };

  interface HTMLAppOpportunitiesElement extends Components.AppOpportunities, HTMLStencilElement {}
  var HTMLAppOpportunitiesElement: {
    prototype: HTMLAppOpportunitiesElement;
    new (): HTMLAppOpportunitiesElement;
  };

  interface HTMLAppResourcesElement extends Components.AppResources, HTMLStencilElement {}
  var HTMLAppResourcesElement: {
    prototype: HTMLAppResourcesElement;
    new (): HTMLAppResourcesElement;
  };

  interface HTMLAppServiceLevelAgreementElement extends Components.AppServiceLevelAgreement, HTMLStencilElement {}
  var HTMLAppServiceLevelAgreementElement: {
    prototype: HTMLAppServiceLevelAgreementElement;
    new (): HTMLAppServiceLevelAgreementElement;
  };

  interface HTMLAppServicesElement extends Components.AppServices, HTMLStencilElement {}
  var HTMLAppServicesElement: {
    prototype: HTMLAppServicesElement;
    new (): HTMLAppServicesElement;
  };

  interface HTMLAppTeamLandingElement extends Components.AppTeamLanding, HTMLStencilElement {}
  var HTMLAppTeamLandingElement: {
    prototype: HTMLAppTeamLandingElement;
    new (): HTMLAppTeamLandingElement;
  };

  interface HTMLAppToolboxElement extends Components.AppToolbox, HTMLStencilElement {}
  var HTMLAppToolboxElement: {
    prototype: HTMLAppToolboxElement;
    new (): HTMLAppToolboxElement;
  };

  interface HTMLAppTosElement extends Components.AppTos, HTMLStencilElement {}
  var HTMLAppTosElement: {
    prototype: HTMLAppTosElement;
    new (): HTMLAppTosElement;
  };

  interface HTMLOpenForgeAppElement extends Components.OpenForgeApp, HTMLStencilElement {}
  var HTMLOpenForgeAppElement: {
    prototype: HTMLOpenForgeAppElement;
    new (): HTMLOpenForgeAppElement;
  };

  interface HTMLElementTagNameMap {
    'app-blog-card': HTMLAppBlogCardElement
    'app-blog-content': HTMLAppBlogContentElement
    'app-blog-featured': HTMLAppBlogFeaturedElement
    'app-carousel-indicators': HTMLAppCarouselIndicatorsElement
    'app-cta': HTMLAppCtaElement
    'app-footer': HTMLAppFooterElement
    'app-img': HTMLAppImgElement
    'lazy-img': HTMLLazyImgElement
    'app-input': HTMLAppInputElement
    'app-members': HTMLAppMembersElement
    'app-nav-header': HTMLAppNavHeaderElement
    'app-radio': HTMLAppRadioElement
    'app-slider': HTMLAppSliderElement
    'app-textarea': HTMLAppTextareaElement
    'app-translate': HTMLAppTranslateElement
    'content-graphic': HTMLContentGraphicElement
    'app-404': HTMLApp404Element
    'app-about': HTMLAppAboutElement
    'app-blog-index': HTMLAppBlogIndexElement
    'app-blog-post': HTMLAppBlogPostElement
    'app-blog': HTMLAppBlogElement
    'app-case-study': HTMLAppCaseStudyElement
    'app-contact': HTMLAppContactElement
    'app-detailed-service': HTMLAppDetailedServiceElement
    'app-home': HTMLAppHomeElement
    'app-opportunities': HTMLAppOpportunitiesElement
    'app-resources': HTMLAppResourcesElement
    'app-service-level-agreement': HTMLAppServiceLevelAgreementElement
    'app-services': HTMLAppServicesElement
    'app-team-landing': HTMLAppTeamLandingElement
    'app-toolbox': HTMLAppToolboxElement
    'app-tos': HTMLAppTosElement
    'open-forge-app': HTMLOpenForgeAppElement
  }

  interface ElementTagNameMap {
    'app-blog-card': HTMLAppBlogCardElement;
    'app-blog-content': HTMLAppBlogContentElement;
    'app-blog-featured': HTMLAppBlogFeaturedElement;
    'app-carousel-indicators': HTMLAppCarouselIndicatorsElement;
    'app-cta': HTMLAppCtaElement;
    'app-footer': HTMLAppFooterElement;
    'app-img': HTMLAppImgElement;
    'lazy-img': HTMLLazyImgElement;
    'app-input': HTMLAppInputElement;
    'app-members': HTMLAppMembersElement;
    'app-nav-header': HTMLAppNavHeaderElement;
    'app-radio': HTMLAppRadioElement;
    'app-slider': HTMLAppSliderElement;
    'app-textarea': HTMLAppTextareaElement;
    'app-translate': HTMLAppTranslateElement;
    'content-graphic': HTMLContentGraphicElement;
    'app-404': HTMLApp404Element;
    'app-about': HTMLAppAboutElement;
    'app-blog-index': HTMLAppBlogIndexElement;
    'app-blog-post': HTMLAppBlogPostElement;
    'app-blog': HTMLAppBlogElement;
    'app-case-study': HTMLAppCaseStudyElement;
    'app-contact': HTMLAppContactElement;
    'app-detailed-service': HTMLAppDetailedServiceElement;
    'app-home': HTMLAppHomeElement;
    'app-opportunities': HTMLAppOpportunitiesElement;
    'app-resources': HTMLAppResourcesElement;
    'app-service-level-agreement': HTMLAppServiceLevelAgreementElement;
    'app-services': HTMLAppServicesElement;
    'app-team-landing': HTMLAppTeamLandingElement;
    'app-toolbox': HTMLAppToolboxElement;
    'app-tos': HTMLAppTosElement;
    'open-forge-app': HTMLOpenForgeAppElement;
  }


  export namespace JSX {
    export interface Element {}
    export interface IntrinsicElements extends StencilIntrinsicElements {
      [tagName: string]: any;
    }
  }
  export interface HTMLAttributes extends StencilHTMLAttributes {}

}
