import { Component, h } from '@stencil/core';
import { translate } from '../../services/translation.service';

@Component({
  tag: 'app-members-section',
})
export class AppMembersSection {
  members = [
    {
      name: 'Jedi Weller',
      image: './../../assets/headshot-jedi.jpg',
      title: translate('about.team.member.title.founder'),
      mail: 'jedi@openforge.io',
      twitter: 'https://twitter.com/jedihacks',
      github: 'https://github.com/jedihacks',
    },
    {
      name: 'Paulina Gallo',
      image: './../../assets/headshot-paulina.png',
      title: translate('about.team.member.title.developer'),
      mail: 'paulina@openforge.io',
      twitter: 'https://twitter.com/paulpaultweets',
      github: 'https://github.com/paulpauldevelops',
      url: '/about/paulina-gallo',
    },
    {
      name: 'Geoffrey Melle',
      image: './../../assets/headshot-geoff.jpg',
      title: translate('about.team.member.title.accountManager'),
      mail: 'geoff@openforge.io',
      twitter: '',
      github: '',
      url: '/about/geoffrey-melle',
    },
    {
      name: 'Rachel Bennett',
      image: './../../assets/headshot-rachel.jpg',
      title: translate('about.team.member.title.designer'),
      mail: 'rachel@openforge.io',
      twitter: '',
      github: '',
      url: '/about/rachel-bennett',
    },
    {
      name: 'Billy Holloran',
      image: './../../assets/headshot-billy.png',
      title: translate('about.team.member.title.qualityManager'),
      mail: 'billy@openforge.io',
      url: '/about/billy-holloran',
    },
    {
      name: 'Ethan Bohan',
      image: './../../assets/headshot-ethan.jpg',
      title: translate('about.team.member.title.designer'),
      mail: 'ethan@openforge.io',
      twitter: '',
      github: '',
      url: '/about/ethan-bohan',
    },
    {
      name: 'Fernando Del Olmo',
      image: './../../assets/headshot-fernando.jpg',
      title: translate('about.team.member.title.developer'),
      mail: 'fernando@openforge.io',
      twitter: 'https://twitter.com/fdom92',
      github: 'https://github.com/Fdom92',
      url: '/about/fernando-del-olmo',
    },
    {
      name: 'Luis Chacon',
      image: './../../assets/headshot-luis.jpg',
      title: translate('about.team.member.title.developer'),
      mail: 'luis@openforge.io',
      twitter: 'https://twitter.com/luiskcs89',
      github: 'https://github.com/luiskcs89',
      url: '/about/luis-chacon',
    },
    {
      name: 'Kevon Chambers',
      image: '/assets/headshot-kevon.png',
      title: translate('about.team.member.title.marketing'),
      mail: 'kevon@openforge.io',
      twitter: '',
      github: '',
    },
    {
      name: 'Sam Hudgens',
      image: './../../assets/headshot-sam.jpg',
      title: translate('about.team.member.title.softwareIntern'),
      mail: 'sam@openforge.io',
      twitter: '',
      github: 'https://github.com/samhudgens',
      url: '/about/sam-hudgens',
    },
    {
      name: 'Young Song',
      image: './../../assets/headshot-young.jpg',
      title: translate('about.team.member.title.softwareIntern'),
      mail: '',
      twitter: 'https://twitter.com/YoungSongJS',
      github: 'https://github.com/Hogusong',
      url: '/about/young-song',
    },
    {
      name: 'Ted Grant',
      image: '/assets/headshot-ted.png',
      title: translate('about.team.member.title.designer'),
      mail: 'ted@openforge.io',
      twitter: '',
      github: '',
      url: '/about/ted-grant',
    },
    {
      name: 'Joni Lehto',
      image: './../../assets/headshot-joni.jpg',
      title: translate('about.team.member.title.developer'),
      mail: 'joni@openforge.io',
      twitter: 'https://twitter.com/lehto_joni',
      github: '',
    },
    {
      name: 'Meredith Alcorn',
      image: './../../assets/headshot-meredith.jpg',
      title: translate('about.team.member.title.developer'),
      mail: 'meredith@openforge.io',
      twitter: '',
      github: 'https://github.com/mmalcorn',
    },
    {
      name: 'Claudio Del Valle',
      image: './../../assets/headshot-claudio.jpg',
      title: translate('about.team.member.title.developer'),
      mail: 'claudio@openforge.io',
      titter: '',
      github: 'https://github.com/daftclaud',
    },
    {
      name: 'Auvo Severinkangas',
      image: './../../assets/headshot-auvo.jpg',
      title: translate('about.team.member.title.developer'),
      mail: 'auvo@openforge.io',
      twitter: '',
      github: '',
    },
    {
      name: 'Dhairya Pujara',
      image: './../../assets/headshot-dhairya.jpg',
      title: translate('about.team.member.title.consultant'),
      mail: '',
      twitter: 'https://twitter.com/dhairyapujara',
      github: '',
    },
    {
      name: 'Eli',
      image: '/assets/headshot-eli.jpg',
      title: 'Entertainment',
      mail: '',
      twitter: '',
      github: '',
      url: 'http://eliluproductions.com/',
      external: true,
    },
    {
      name: 'Lu',
      image: '/assets/headshot-lu.jpg',
      title: 'Entertainment',
      mail: '',
      twitter: '',
      github: '',
      url: 'http://eliluproductions.com/',
      external: true,
    },
    {
      name: 'Casey',
      image: './../../assets/headshot-casey.jpg',
      title: translate('about.team.member.title.officer'),
      mail: '',
      twitter: '',
      github: '',
      url: '/about/casey',
    },
    // {
    //   name: 'YOU?',
    //   image: '/assets/headshot-placeholder.jpg',
    //   title: '',
    //   mail: 'geoff@openforge.io',
    //   twitter: '',
    //   github: '',
    //   url: '/opportunities/develop',
    // },
  ];

  render() {
    return <app-members members={this.members} />;
  }
}
